
services:
  db:
    image: postgres:13
    container_name: warent_postgres_db
    environment:
      POSTGRES_USER: warent_user
      POSTGRES_PASSWORD: your_strong_password
      POSTGRES_DB: warent_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: